
version: '3'
services:

    public-relay-list:
        build: ./public-relay-list
        hostname: public-relay-list
        ports:
            - "8080:8080"
        networks:
            private-network:
                ipv4_address: 10.1.2.200

    relay0:
        build: ./security
        hostname: relay0
        environment:
            - PORT=9000
            - PUBLIC_RELAY_LIST=http://10.1.2.200:8080
        networks:
            private-network:
                ipv4_address: 10.1.2.100
        depends_on:
            public-relay-list:
                condition: service_started

    relay1:
        build: ./security
        hostname: relay1
        environment:
            - PORT=9000
            - PUBLIC_RELAY_LIST=http://10.1.2.200:8080
        networks:
            private-network:
                ipv4_address: 10.1.2.101
        depends_on:
            public-relay-list:
                condition: service_started

    relay2:
        build: ./security
        hostname: relay2
        environment:
            - PORT=9000
            - PUBLIC_RELAY_LIST=http://10.1.2.200:8080
        networks:
            private-network:
                ipv4_address: 10.1.2.102
        depends_on:
            public-relay-list:
                condition: service_started

    relay3:
        build: ./security
        hostname: relay3
        environment:
            - PORT=9000
            - PUBLIC_RELAY_LIST=http://10.1.2.200:8080
        networks:
            private-network:
                ipv4_address: 10.1.2.103
        depends_on:
            public-relay-list:
                condition: service_started

    relay4:
        build: ./security
        hostname: relay4
        environment:
            - PORT=9000
            - PUBLIC_RELAY_LIST=http://10.1.2.200:8080
        networks:
            private-network:
                ipv4_address: 10.1.2.104
        depends_on:
            public-relay-list:
                condition: service_started

    relay5:
        build: ./security
        hostname: relay5
        environment:
            - PORT=9000
            - PUBLIC_RELAY_LIST=http://10.1.2.200:8080
        networks:
            private-network:
                ipv4_address: 10.1.2.105
        depends_on:
            public-relay-list:
                condition: service_started

    relay6:
        build: ./security
        hostname: relay6
        environment:
            - PORT=9000
            - PUBLIC_RELAY_LIST=http://10.1.2.200:8080
        networks:
            private-network:
                ipv4_address: 10.1.2.106
        depends_on:
            public-relay-list:
                condition: service_started

    relay7:
        build: ./security
        hostname: relay7
        environment:
            - PORT=9000
            - PUBLIC_RELAY_LIST=http://10.1.2.200:8080
        networks:
            private-network:
                ipv4_address: 10.1.2.107
        depends_on:
            public-relay-list:
                condition: service_started

    relay8:
        build: ./security
        hostname: relay8
        environment:
            - PORT=9000
            - PUBLIC_RELAY_LIST=http://10.1.2.200:8080
        networks:
            private-network:
                ipv4_address: 10.1.2.108
        depends_on:
            public-relay-list:
                condition: service_started

    relay9:
        build: ./security
        hostname: relay9
        environment:
            - PORT=9000
            - PUBLIC_RELAY_LIST=http://10.1.2.200:8080
        networks:
            private-network:
                ipv4_address: 10.1.2.109
        depends_on:
            public-relay-list:
                condition: service_started

networks:
  private-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/24
